language: python
python:
    - "3.5"
before_install:
    - pip install pytest pytest-cov
    - pip install coveralls
before_script:
    # make sure we are testing the newest chemkin.py
    - sh make_chemkin.sh
script:
    - py.test
after_success:
    - coveralls
