language: python
python:
    - "3.5"
    - "3.6"
before_install:
    - pip install pytest pytest-cov coveralls
script:
    - ls
    - py.test
after_success:
    - coveralls
    
    # test install from pip
    - rm -rf pychemkin
    - rm -rf setup.py
    - pip install pychemkin
    - ls
    - py.test
